### PR TITLE
44579 document app config

### PR DESCRIPTION
**Pull request by connerleverett**
Add components config description to API.
Bump dependencies.

### CODE REVIEW

**Comment by connerleverett** [comment]
@eric-parsons Would you be able to write a preamble for the Components page (`api-compondents.mdx`)?

**Comment by connerleverett** [comment]
@eric-parsons I'm also seeing the build fail because of prettier. When I run prettier locally it changes every file (but then in VSCode when I look at the diff nothing has changed) I'm assuming this is because of linux/windows ? Wondering what you suggest moving forward (either get rid of prettier as part of the build step? Or pushing all the "changed" files, some other solution?)

**Comment by eric-parsons** [comment]
> @eric-parsons I'm also seeing the build fail because of prettier. When I run prettier locally it changes every file (but then in VSCode when I look at the diff nothing has changed) I'm assuming this is because of linux/windows ? Wondering what you suggest moving forward: get rid of prettier as part of the build step? Push all the "changed" files? Some other solution?

Typically Prettier isn't part of the build step, but rather something that is run before committing. Our various Web-related projects have Prettier set up to run as a pre-commit hook, which I think would be more ideal. We used to use husky+pretty-quick, but I found it didn't work reliably, so I switched it to simple-git-hooks+lint-staged. 

As far as line endings go, typically most projects enforce that all files are committed using Unix line endings in the actual repo (`\n`). Windows users should use the `autocrlf` to auto convert to and from Windows-style to Unix style on checkout and commit. This can be configured in .gitattributes in the repo so that people don't have to configure it manually. More details available [here](https://prettier.io/docs/en/options.html#end-of-line).

**Comment by connerleverett** [comment]
@eric-parsons the build completed so you can take a look at the preview by clicking here: 
image

**Comment by eric-parsons** [comment]
@connerleverett, this might not be possible with the current app config schemas we have, but I think that this API reference would be more useful if it was organized like the Command/Operation/Events one is, like this:
image

Right now, the model types are mixed in among all the secondary types that they reference. It would be more helpful to have all of the top-level model types appear first. Also, this reference contains models for both components *and* services, so models could be even further subdivided into these two categories (and the name of the section should also be updated).

In the case of components, there is also another issue: there isn't always an obvious or 1:1 relationship between components and models. For example, toolbar and IWTM both use MenuModel as their model. Buttons use MenuItemModel. The results list and results table both use ResultsModel. And so on. It would be nice to be able to list actual component types followed by their model. 

Something to think about as a future improvement? We would probably have to figure out how to generate the additional metadata needed.

**Comment by eric-parsons** [comment]
I'm seeing a lot of stuff like this in the output:

image

Glancing at the source schemas, I think that the needed information for the symbol types should all be in there? Not sure why this is happening.

**Comment by eric-parsons** [comment]
> @eric-parsons the build completed so you can take a look at the preview by clicking here:
> image

Done. There really isn't a lot to say yet, since at the moment it's just app config JSON. In the future we could expand it when some of my suggested improvements are implemented. I also renamed the page to mention services, since it's not limited to components.

**Pull request merged**
